### ISSUE TITLE
Sickrage ebuild corrupted

### ISSUE THREAD

**Issue by viddi87** [daktak/gentoo#10]
Can't emerge sickrage, ebuild not matching signatures

**Comment by blade2005** [comment]
So much this, 
`* Digest verification failed:
 * /var/lib/layman/daktak/net-nntp/sickrage/sickrage-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2328
 * Expected: 2352
`

@daktak this should be a simple matter of updating recorded size to match

**Comment by viddi87** [comment]
Need to update Manifest

**Comment by daktak** [comment]
Updated, I'm not currently using sickrage, so maybe  salfter's overlay man be more stable.
