### ISSUE TITLE
I2P Overlay Collaboration: Let Our Powers Combine

### ISSUE THREAD

**Issue by leycec** [daktak/gentoo#7]
Top of the Canadian morning to you, Señor daktak. :sun_with_face: 

I couldn't help but note, on casual perusing `i2p gentoo` search hits, _yet another_ third-party `net-i2p/i2p` ebuild: **yours**. That's cool, man! Don't get me wrong. The more the anonymized the better.

That said, I2P on Gentoo _is_ a tad outrageous. The [Portage tree](https://packages.gentoo.org/package/net-p2p/i2p), [nektoo](https://bitbucket.org/neko259/nektoo) overlay, [powerman](https://github.com/powerman/powerman-overlay) overlay, your overlay, and my [raiagent](https://github.com/leycec/raiagent) overlay all publish `net-i2p/i2p` ebuilds of varying versions and reliability. It would be _sweet ambrosia from the Gods_ if Gentoo's overlay community could come to some semblance of a consensus. (Probably infeasible, I admit.)

At the moment, there exist two distinct I2P ebuild lines:
- **The old-school I2P ebuild,** originally developed by _God-and-Satan-only-knows-who_ and since maintained by powerman, nektoo, and now your esteemable overlay (in that chronological order).
- **The new-school I2P ebuild,** originally developed by Gentoo Developer [Daniel Campbell (zlg)](http://euscan.gentooexperimental.org/maintainers/zlg@gentoo.org) for the Portage tree and since unofficially improved by... well, _[me](https://github.com/leycec/raiagent/blob/master/net-p2p/i2p/i2p-0.9.21.ebuild)_.

It's probably no surprise that the latter substantially improves upon the former. With accurate dependencies, licenses, service files, USE flags, and so on, zlg's new-school I2P ebuild is a clear win-win. My [recent refactoring](https://github.com/leycec/raiagent/blob/master/net-p2p/i2p/i2p-0.9.21.ebuild) further improves upon his hard work with additional dependencies, commentary, and `sed`\- rather than `patch`-based patching.

For some oddball (but possibly justifiable) reason, zlg elected to use hardcoded unified diffs rather than installation-time `sed` commands for patching the I2P codebase. While this may have seemed like a good idea at the time, the unified diffs break on _every_ I2P version bump and hence have to be regenerated by hand – which isn't useful for anyone's sanity. My refactoring reverts these diffs back into `sed` statements while preserving all improvements introduced by these diffs. **[Read:** I didn't just lift the older `sed` statements from the old-school I2P ebuild.**]**

I'd like to advocate that all newer I2P ebuilds fork either the [official Portage](https://packages.gentoo.org/package/net-p2p/i2p) _or_ [unofficial raiagent](https://github.com/leycec/raiagent/blob/master/net-p2p/i2p/i2p-0.9.21.ebuild) versions. Your mileage may vary, of course – but it'd be great if we could begin to pool our I2P contributions rather than continually reinventing the I2P wheel.

![Let Our Powers Combine](http://nerdist.com/wp-content/uploads/2015/04/planet-header-970x545.jpg)

**Comment by daktak** [comment]
Portage is newer than this version, removed and closing.
